version: "3.8"

services:
    php:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        container_name: laravel_php
        volumes:
            - ../:/var/www
        networks:
            - app_network

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "80:80"
        volumes:
            - ../:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - app_network

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret123

        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app_network

volumes:
    mysql_data:

networks:
    app_network:
