name: Deploy Laravel to EC2 Amazon Linux 2023

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: |
            github.com

      - name: Add EC2 to known_hosts
        run: ssh-keyscan -H 16.176.62.144 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ec2-user@16.176.62.144 << 'EOF'
            cd /var/www/devbt
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo systemctl reload nginx
          EOF
